# Python Refresher

This document is a personal go-to cheatsheet for some concepts of Python that came to be usueful for me at some points. Most or even all of them can be easily found on common reference guides on the internet.

[Jupyter Notebook Shortcuts](https://towardsdatascience.com/jypyter-notebook-shortcuts-bf0101a98330)  

[Markdown Guide](https://www.markdownguide.org/)  
[How to add new line in a Markdown](https://stackoverflow.com/questions/33191744/how-to-add-new-line-in-markdown-presentation/33191810)  

[The Python Tutorial](https://docs.python.org/3/tutorial/index.html)  
[Python Tips](https://book.pythontips.com/en/latest/index.html)  
[Python 3 Module of the Week](https://book.pythontips.com/en/latest/generators.html)  
[PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/)  
[PEP 257 -- Docstring Conventions](https://www.python.org/dev/peps/pep-0257/)  

[Managing Environments in Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)  
[Conda Cheatsheet](https://docs.conda.io/projects/conda/en/latest/user-guide/cheatsheet.html)

## Virtual Environments and `Pip` command

Virtual environents helps isolating packages imports from one project to another. You can read more about it [here](https://docs.python.org/3/tutorial/venv.html).

I find the following most useful to me :
- `pip freeze > requirements.txt`
- `pip install -r requirements.txt`

Also you can use [`conda`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#) which I want more complete.  

```
conda create -n myenv python=3.7.6
conda activate myenv
conda env list
pip freeze

pip install --upgrade jupyter
jupyter notebook

conda deactivate
conda remove -n myenv --all
conda env list
```

Update all packages `pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U`

## Data Types and Operators

In [14]:
# the modulo operator % returns the remainder of the division
print('{} modulo {} is {}'.format(7, 2, 7 % 2))

# the floordiv operator // returns the rounding down of the division
print('{} floordiv by {} is {}'.format(7, 2, 7 // 2))
print('{} floordiv by {} is {}'.format(-7, 2, -7 // 2))

7 modulo 2 is 1
7 floordiv by 2 is 3
-7 floordiv by 2 is -4


## Lambda, Map, Filter, Reduce

`lambda` helps writing small on-the-go functions. It can be seen as the mathematical equvalent of `f(x) = x + 2` for example. 

In [19]:
x_plus_two = lambda x: x + 2
x_plus_two(10)

12

We can apply a function to a list by using `map`. The function returns a `map` object, so we will use `list`to convert into a list.

In [27]:
list(map(lambda x: x ** 2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

You can apply a function to only a subset of a list using `filter`

In [28]:
list(filter(lambda x: x < 0, range(-5,5)))

[-5, -4, -3, -2, -1]

You can apply a rolling computation to a list using `reduce`

In [33]:
from functools import reduce
reduce((lambda x, y: x * y), range(1,5)) # returns factorial of 4

24

## Numpy

If the package is not present in `!conda list numpy` let's start by installing it `conda install numpy=1.18.1`.

In [24]:
import numpy as np
from time import time

x = np.random.random(10**8) # returns a list of 10**8 random values between 0 and 1

start = time()
sum(x) / len(x)
print('It took {:.2f}s to run'.format(time() - start))

start = time()
np.mean(x)
print('While numpy on takes {:.2f}s to run'.format(time() - start))

It took 19.93s to run
While numpy on takes 0.07s to run


In [39]:
x = np.array([1, 2, 3, 4.5, 5])
print('x = ', x) # Numpy uses upcasting since all elements must be of the same type

x = np.array([1, 2, 3, 4.5, 5], dtype=np.int64)
print('x = ', x) # We can for the type of the elements

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('x has a total of', x.size, 'elements')
print('The elements in x are of type:', x.dtype)

np.save('my_array', x * 2) # it is possible to save the file into my_array.npy
y = np.load('my_array.npy') # and load it 
print('y = ', y)

x =  [1.  2.  3.  4.5 5. ]
x =  [1 2 3 4 5]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
x has a total of 5 elements
The elements in x are of type: int64
y =  [ 2  4  6  8 10]


In [40]:
X = np.zeros((3,4))
print('X = \n', X)

X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
X = np.ones((3,4))
print('X = \n', X)

X = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
X = np.full((3,4), 5)
print('X = \n', X)

X = 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [46]:
X = np.eye(3)
print('X = \n', X)

X = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
X = np.diag([1, 2, 3])
print('X = \n', X)

X = 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [53]:
X = np.arange(10)
print('X = \n', X)

X = 
 [0 1 2 3 4 5 6 7 8 9]


In [61]:
X = np.linspace(0, 3, 7)
print('X = \n', X)

X = 
 [0.  0.5 1.  1.5 2.  2.5 3. ]


In [70]:
X = np.arange(20).reshape(-1, 10) # we can unspecify one dimension and let Numpy guess it
print('X = \n', X)

X = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


`random` is very useful when generating numbers, [more](https://docs.python.org/3/library/random.html)  
Other functions include: `delete, insert, append, extend, vstack, hstack, copy, diag, unique, sort, ...`  
Arithmetic oprators include: `exp, sqrt, mean, min, max, median, sum, power, std ...` 

## Pandas

If the package is not present in `!conda list pandas` let's start by installing it `conda install pandas=1.0.3`.

`pd.Series(data, index), loc, iloc, drop, pd.DataFrame(dict, index), rename, set_index, isnull, count, dropna, fillna, interpolate, any, read_csv, head, tail, describe, corr, groupby, pd.date_range, join, rolling, query ...` 